config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
]

products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('products/create', views.AddProductView.as_view(), name='product_create'),
    path('products/create/custom', views.AddProductCustomFormView.as_view(), name='product_create_custom_form'),

]

products/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'


class SubCategory(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Subcategories'


class Product(models.Model):
    name = models.CharField(max_length=50)
    prize = models.DecimalField(decimal_places=2, max_digits=9)
    description = models.TextField()
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='products')
    subcategory = models.ManyToManyField('SubCategory', related_name='products')

    def __str__(self):
        return self.name

products/forms.py
from django import forms

from . import models


class ProductForm(forms.ModelForm):
    class Meta:
        model = models.Product
        fields = ('name', 'prize', 'description', 'category', 'subcategory')


class ProductFormCustom(forms.Form):
    name = forms.CharField(label='Name')
    prize = forms.DecimalField(label='Price')
    description = forms.CharField(label='Description')
    category = forms.ChoiceField(label='Category', choices=tuple())
    subcategory = forms.MultipleChoiceField(label='Subcategory', choices=tuple())

products/views.py
from django import views
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import generic

from . import forms
from . import models


class HomeView(generic.ListView):
    queryset = models.Product.objects.all()
    template_name = 'products/home.html'
    context_object_name = 'products'


class AddProductView(views.View):
    def get(self, request):
        form = forms.ProductForm()
        return render(request, 'products/product_create.html', {'form': form})

    def post(self, request):
        form = forms.ProductForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('products:home'))
        return render(request, 'products/product_create.html', {'form': form})


class AddProductCustomFormView(views.View):
    categories = [(cat.id, cat.name) for cat in models.Category.objects.all()]
    subcategories = [(scat.id, scat.name) for scat in models.SubCategory.objects.all()]

    def get(self, request):
        form = forms.ProductFormCustom()
        form.fields['category'].choices = self.categories
        form.fields['subcategory'].choices = self.subcategories
        return render(request, 'products/product_create.html', {'form': form})

    def post(self, request):
        form = forms.ProductFormCustom(request.POST)
        form.fields['category'].choices = self.categories
        form.fields['subcategory'].choices = self.subcategories

        if form.is_valid():
            name, prize, description, category, subcategories, *rest = [*form.cleaned_data.values()]

            ct = models.Category.objects.get(pk=category)
            sb = models.SubCategory.objects.filter(pk__in=subcategories)

            product = models.Product(name=name, prize=prize, description=description, category=ct)
            product.save()
            for s in sb:
                product.subcategory.add(s)

            product.save()

            return redirect(reverse('products:home'))
        return render(request, 'products/product_create.html', {'form': form})

products/templates/products/home.html
{% extends 'base.html' %}

{% block container %}
    <h1>Products</h1>
    <ul class="list-group list-group-flush">
        {% for product in products %}
            <li class="list-group-item"><b>{{ product.name }}</b>, {{ product.prize }}, category: <b>{{ product.category }}</b>,
                <ul>
                    {% for subcategory in product.subcategory.all %}
                        <li>subcategory: <b>{{ subcategory }}</b></li>
                    {% endfor %}
                </ul>
            </li>
        {% empty %}
            <p>No products found!</p>
        {% endfor %}
    </ul>
{% endblock %}

products/templates/products/product_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block container %}
    <h1>Add Product</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Add</button>
    </form>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>☕️ CoffeeShop {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}" async defer></script>
</head>
<body>

{% include 'partials/_nav.html' %}


<div class="container mt-3">
    <div class="row">
        <div class="col-12 col-md-8">
            {% block container %}

            {% endblock %}
        </div>
        <aside class="col-12 col-md-4">
            {% block aside %}

            {% endblock %}
        </aside>
    </div>
</div>


</body>
</html>

templates/partials/_nav.html
{% load static %}
<nav class="navbar navbar-expand-md bg-primary" data-bs-theme="dark">
    <div class="container">
        <a class="navbar-brand" href="#">
            <img src="{% static 'images/logo.svg' %}" class="logo" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'products:product_create' %}">Add
                        Product with Model Form</a>
                </li>
                <li class="nav-item">
                   <a class="nav-link active" aria-current="page" href="{% url 'products:product_create_custom_form' %}">Add
                        Product with Custom Form</a>
                </li>
            </ul>
        </div>
    </div>
</nav>